version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    # 分支匹配
    branches:
      include:
        - master
    # git 提交信息匹配，匹配 build: xxxx 这样的格式
    commitMessages:
      include:
        - '^build\:.*'
# 引用仓库变量
variables:
  global:
    - TEST_VAR
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - npm install -g @jsdevtools/npm-publish@1
          - npm-publish --token=${TEST_VAR} ./package.json
